---
title: "10. Assessment of the Northern Rockfish stock in the Gulf of Alaska"
output: 
  bookdown::word_document2:
    reference_docx: "template.docx"
    toc: false
    number_sections: false

always_allow_html: true        
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in
      
fig_caption: true
bibliography: "safe_bibby.bib"
csl: "fishfish.csl"

author: "Benjamin C. Williams, Peter-John F. Hulson, Chris R. Lunsford, Curry J. Cunningham, Dana H. Hanselman"
date: "September 2020"
---
\pagenumbering{gobble}

```{r setup, include=FALSE, echo = FALSE}
# remotes::install_github("crsh/rmdfiltr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(eval.after = "fig.cap")
```

```{r load, warning=F, message=F}
library(dplyr)
year = 2020
model = "m18.2b"
end_proj = year + 15
```
```{r load2, eval = T}

catch = read.csv(here::here(year, "data/output/catch.csv"))
```


```{r, child=c("01-summary.Rmd", "02-table.Rmd", "03-responses.Rmd"), eval = T}

```


```{r, child = c("04-intro.Rmd", "05-fishery.Rmd", "06-data.Rmd", "07-model.Rmd"), eval = T}

```

```{r, child = c("08-results.Rmd", "09-abc.Rmd", "10-ecosystem.Rmd", "11-gaps.Rmd"), eval = T}

```
\pagebreak

# References {-}
<div id="refs"></div>

\pagebreak

```{r, child = c("12-tables.Rmd", "13-figures.Rmd"), eval = T}

```

\pagebreak

```{r, child = c("14-append_a.Rmd", "15-append_vast.Rmd"), eval = T}

```
