# Data

Operational Update: The data description for northern rockfish has been truncated to highlight relevant updates or changes made for this cycle. 
The reader is referred to the last full assessment (Williams et al. 2023) for the entirety of this section. 


The following table summarizes the data used in the stock assessment model for northern rockfish (* denotes new data for this assessment):

```{r}

data.frame(Source = c(rep("NMFS Groundfish survey", 2),
                      rep("U.S. trawl fishery", 3)),
           Data = c("Survey biomass",
                    "Age composition",
                    "Catch",
                    "Age composition",
                    "Length composition"),
           Years = c("1990-1999 (triennial), 2001-2021 (biennial), 2023*",
                     "1990-1999 (triennial), 2003-2021 (biennial), 2023*",
                     "1961-2020, 2021-2024*",
                     "1998-2002, 2004-2006, 2008-2020 (biennial), 2022*",
                     "1991-1997, 2003, 2007-2021 (biennial), 2023*"))  %>% 
  flextable::flextable() %>% 
    flextable::width(j = ~ Source, width = 1) %>% 
    flextable::width(j = ~ Data, width = 1.5) %>% 
   flextable::width(j = ~ Years, width = 4) %>% 
   flextable::merge_v(j = 1) %>% 
  flextable::font(fontname = "Times", part = "all") %>% 
   flextable::padding(padding = 0, part = "all") %>% 
  flextable::fontsize(size = 10) %>% 
  flextable::theme_vanilla() %>% 
  flextable::fix_border_issues() 

```

## Fishery

Catches as used in the model are shown in Table 10-\@ref(tab:tcatch); discards are not used in the model. 
Fishery-dependent compositional data (catch-at-length and catch-at-age, and associated input sample sizes) are shown in Table 10-\@ref(tab:tfsc) and Table 10-\@ref(tab:tfac), respectively. 


## Survey

Survey biomass estimates and associated sampling variability (annual CVs) are shown in Table 10-\@ref(tab:tvast). 
Suvey compositional data (survey catch-at-age and associated input sample sizes) are shown in Table 10-\@ref(tab:tsac). 
This assessment includes a new survey observation for 2025, which was lower than previous survey data. 

