# Tables

```{r tcatch, eval = T}
library(dplyr)
vroom::vroom(here::here(year, 'data', 'output', 'fish_catch.csv')) %>%
  dplyr::rename(Year=year, Catch = catch) %>% 
  dplyr::left_join(vroom::vroom(here::here(year, "data", "user_input", "abc_tac.csv"))) %>% 
  dplyr::select(Year, Foreign, `Joint Venture` = Joint, Domestic, Total = Catch, ABC, TAC) %>% 
  dplyr::mutate(ptac = round(Total / TAC * 100),
                Foreign = ifelse(Foreign==0, 1, Foreign),
                `Joint Venture` = ifelse(`Joint Venture`==0, 1, `Joint Venture`)) -> dat 


flextable::flextable(dat) %>% 
  flextable::colformat_double(j=2:7, digit=0 ) %>% 
  flextable::colformat_double(j=1, big.mark = "", digit=0) %>% 
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::set_header_labels(ptac = "% TAC") %>% 
  flextable::align(j=1, part="all") %>% 
  flextable::autofit() %>% 
  flextable::footnote(
    i=28, j=1,part="body",
    value = flextable::as_paragraph("Slope rockfish assemblage management implemented by NPFMC."),
    ref_symbol = "1") %>% 
  flextable::footnote(
    i=31, j=1, part = "body",
    value = flextable::as_paragraph("Slope rockfish divided into 3 management subgroups:  Pacific ocean perch, shortraker/ rougheye, and other slope rockfish."),
    ref_symbol = "2") %>% 
  flextable::footnote(
    i=33, j=1, part="body",
    value = flextable::as_paragraph("A fourth management subgroup, northern rockfish, was created."),
    ref_symbol = "3") %>% 
  flextable::footnote(
    i=47, j=1, part="body",
    value = flextable::as_paragraph("Central Gulf Rockfish Pilot Project implemented for rockfish fishery."),
    ref_symbol = "4") %>% 
  flextable::footnote(
    i=64, j=1, part="body",
    value = flextable::as_paragraph("Catch through 2024-10-16."),
    ref_symbol = "5") %>% 
   flextable::set_caption("Commercial catch (t) of dusky rockfish in the Gulf of Alaska, with Gulf-wide values of acceptable biological catch (ABC), total allowable catch (TAC), and percent TAC harvested (% TAC). Values are a combination of foreign observer data, joint venture catch data, and NMFS Regional Office Catch Accounting System data.") %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::padding(padding = 0.05, part = "all")  %>% 
  flextable::font(fontname = "Times New Roman", part = "all")
```

\pagebreak


```{r fmp-bycatch}

read.csv(here::here(year, "data", "output", "fmp_catch.csv")) %>%
  dplyr::group_by(year, species) %>% 
  dplyr::summarise(c = sum(conf),
                   weight = sum(catch)) %>% 
  dplyr::mutate(value = ifelse(c<=3, NA,  weight)) %>% 
  # dplyr::ungroup() %>% 
  # dplyr::mutate(value = ifelse(!is.na(value), round(value,0), "Conf")) %>% 
  dplyr::select(-c(c, weight)) %>% 
  tidyr::pivot_wider(names_from=year, values_from = value) %>% 
  # dplyr::mutate(dplyr::across(dplyr::everything(), ~tidyr::replace_na(.x, "-"))) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0.5, part = "all")  %>%  
  flextable::autofit() %>% 
  flextable::set_header_labels(values = 
                                 list(species = "Species Group")) %>% 
  flextable::colformat_double(j=2:7, digit=0) %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("FMP species incidental catch estimates in tons for Gulf of Alaska rockfish targeted fisheries. Blanks = Confidential because of less than three vessels, or not caught. Source: NMFS AKRO Blend/Catch Accounting System via AKFIN 2022-10-28.")
```

\pagebreak

```{r nonfmp-bycatch}

vroom::vroom(here::here(year, "data", "output", "non-fmp_catch.csv")) %>% 
  dplyr::select(year = Year, 
                species = `Species Group Name`,
                conf = `Conf Flag`,
                weight = `Nontarget Estimate (mt)`,
                count = `Nontarget Species Count (Sum)`) %>% 
  filter(year>2019) %>% 
  dplyr::group_by(year, species) %>% 
  dplyr::summarise(c = sum(conf),
                   weight = sum(weight),
                   count = sum(count)) %>% 
  dplyr::mutate(value = dplyr::case_when(!is.na(weight) & c>3 ~ weight,
                                         !is.na(count) & c>3 ~ count),
                value = ifelse(is.na(value), "Conf", round(value,2))) %>% 
  dplyr::select(-c(c, weight, count)) %>% 
  tidyr::pivot_wider(names_from=year, values_from = value) %>% 
  dplyr::mutate(dplyr::across(dplyr::everything(), ~tidyr::replace_na(.x, "-"))) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0.5, part = "all")  %>%  
  flextable::autofit() %>% 
  flextable::set_header_labels(values = 
                                 list(species = "Species Group")) %>% 
  flextable::colformat_double(j=2:6, digit=0) %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Non-FMP species bycatch estimates in tons for Gulf of Alaska rockfish targeted fisheries. Conf. = Confidential because of less than three vessels. Source: NMFS AKRO Blend/Catch Accounting System via AKFIN 2022-10-28.")
```

\pagebreak

```{r psc}
read.csv(here::here(year, "data", "output", "psc_catch.csv")) %>%
  dplyr::select(species, X2020, X2021, X2022, X2023, X2024) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0, part = "all")  %>%  
  flextable::autofit() %>% 
  flextable::set_header_labels(values = 
                                 list(species_group_name = "Species Group",
                                      X2020 = "2020",
                                      X2021 = "2021",
                                      X2022 = "2022",
                                      X2023 = "2023",
                                      X2024 = "2024")) %>% 
  flextable::colformat_double(j=2:6, digit=0) %>% 
  flextable::set_caption("Prohibited Species Catch (PSC) estimates reported in tons for halibut and herring, and thousands of animals for crab and salmon, by year, for the GOA rockfish fishery 2014-2018. Source: NMFS AKRO Blend/Catch Accounting System PSCNQ via AKFIN 2022-10-28.")
```

\pagebreak


```{r discard}
data.frame(year = 1993:2003,
           perc = c(26.5,17.7,12.7,16.6,28.0,18.4,11.3,10.0,17.7,10.0,9.4),
           year1 = c(2004:2014),
           perc1 = c(7.8,4.2,9.1,2.6,4.9,3.1,1.5,3.9,2.5,4.1,3.8),
           year2 = c(2015:2024, NA),
           perc2 = c(4.6,5.5,7.9,3.6,5.6,1.4,1.6,1.5,1.9, 6.1, NA)) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all") %>% 
  flextable::colformat_num(j=c(1,3, 5), 
                           big.mark = "") %>% 
  flextable::set_header_labels(values = list(year = "Year", year1 = "Year", year2 = "Year", perc = "% discard", perc1 ="% discard", perc2 = "% discard")) %>% 
  flextable::align(j=c(1,3), part = 'all') %>% 
  flextable::width(j=1:6, width=0.5) %>%   
  flextable::align(j=1:6, align = "center", part = 'all') %>%
  flextable::padding(padding = 0.8, part = "all") %>% 
  flextable::border_remove() %>%
  flextable::hline_top(part = "header") %>%
  flextable::hline_top() %>% 
  flextable::hline_bottom() %>%
  flextable::set_caption("Gulf of Alaska discard rates rates (percent of the total catch discarded within management categories) of northern rockfish.")

```
\pagebreak

```{r mgmt}

vroom::vroom(here::here(year, "data", "user_input", "abc_tac.csv")) %>% 
  dplyr::select(Year, Measure = measure) %>% 
  tidyr::drop_na() %>% 
  flextable::flextable() %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::align(j=1, part = 'all') %>% 
  flextable::colformat_double(j=1, 
                              big.mark = "",
                              digits=0) %>% 
  flextable::width(j=2, width=4.5) %>% 
   flextable::border_remove() %>%
  flextable::hline_top(part = "header") %>%
  flextable::hline_top() %>% 
  flextable::hline_bottom() %>% 
  flextable::padding(padding = 0.7, part = "all") %>%   
    flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Summary of key management measures for northern rockfish in the Gulf of Alaska.")

```
\pagebreak

```{r tfsc, eval = T}

  rbind(as.data.frame(readRDS(here::here(year, 'm24', 'dat.rds'))$fish_size_obs),
        readRDS(here::here(year, 'm24', 'dat.rds'))$fish_size_iss) -> obs
  names(obs) = readRDS(here::here(year, 'm24', 'dat.rds'))$fish_size_yrs
  mutate(obs, `Length (cm)` = c(readRDS(here::here(year, 'm24', 'dat.rds'))$length_bins, "Sample size")) %>% 
    dplyr::relocate(`Length (cm)`) %>% 
   dplyr::mutate(dplyr::across(2:18, round, 3)) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 9, part = "all") %>% 
    flextable::colformat_double(i=32, digit=1) %>% 
  flextable::padding(padding = 0.8, part = "all")  %>%  
  flextable::autofit() %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Fishery length compositions for northern rockfish in the Gulf of Alaska. Lengths below 15 are pooled and lengths greater than 45 are pooled. Survey size compositions are not used in model.")

```

\pagebreak

```{r tfac, eval = T}

  rbind(as.data.frame(readRDS(here::here(year, 'm24', 'dat.rds'))$fish_age_obs),
        readRDS(here::here(year, 'm24', 'dat.rds'))$fish_age_iss) -> obs
  names(obs) = readRDS(here::here(year, 'm24', 'dat.rds'))$fish_age_yrs
  mutate(obs, Age = c(readRDS(here::here(year, 'm24', 'dat.rds'))$ages, "Sample size")) %>% 
    dplyr::relocate(`Age`) %>%
    dplyr::mutate(dplyr::across(2:17, round, 3)) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 9, part = "all") %>% 
  flextable::padding(padding = 0.5, part = "all")  %>%  
  flextable::colformat_double(i=45, digit=1) %>% 
  flextable::autofit() %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Fishery age compositions for northern rockfish in the Gulf of Alaska.")
```

\pagebreak
    
```{r tvast}
read.csv(here::here(year, "data", "user_input", "vast_lognormal.csv")) %>%
  dplyr::mutate(dplyr::across(2:5, round, 0)) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0.8, part = "all")  %>%  
  flextable::set_header_labels(values = 
                                 list(year = 'Year',
                                      biomass = "Biomass (t)",
                                      se = "SE",
                                      lci = 'Lower CI',
                                      uci = "Upper CI")) %>% 
  flextable::colformat_num(j=1, big.mark = "") %>% 
  flextable::autofit() %>% 
  flextable::align(j=1, part= "all") %>%
  flextable::set_caption("GOA northern rockfish biomass estimates, standard errors, and confidence intervals, based on results of NMFS bottom trawl surveys using a geostatistical general linear mixed model (VAST) estimator used in model 24.")
```
<br>

```{r tdb}
read.csv(here::here(year, "data", "output", "goa_total_bts_biomass.csv")) %>%
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0.5, part = "all")  %>%  
  flextable::set_header_labels(values = 
                                 list(year = 'Year',
                                      biomass = "Biomass (t)",
                                      se = "SE",
                                      lci = 'Lower CI',
                                      uci = "Upper CI")) %>% 
  flextable::colformat_num(j=1, big.mark = "") %>% 
  flextable::autofit() %>% 
  flextable::align(j=1, part= "all") %>%
  flextable::set_caption("GOA northern rockfish biomass estimates, standard errors, and confidence intervals, based on results of NMFS bottom trawl surveys using a design-based estimator.")

```

\pagebreak

```{r tsac, eval = T}

  rbind(as.data.frame(readRDS(here::here(year, 'm24', 'dat.rds'))$srv_age_obs),
        readRDS(here::here(year, 'm24', 'dat.rds'))$srv_age_iss) -> obs
  names(obs) = readRDS(here::here(year, 'm24', 'dat.rds'))$srv_age_yrs
  mutate(obs, Age = c(readRDS(here::here(year, 'm24', 'dat.rds'))$ages, "Sample size")) %>% 
    dplyr::relocate(`Age`) %>%
    dplyr::mutate(dplyr::across(2:17, \(x) round(x, 3))) %>% 
    dplyr::mutate(dplyr::across(2:17, \(x) round(x, 3))) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
    flextable::colformat_double(i=45, digit=1) %>% 
  flextable::fontsize(size = 9, part = "all") %>% 
  flextable::padding(padding = 0.5, part = "all")  %>%  
  flextable::autofit() %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Survey age compositions for northern rockfish in the Gulf of Alaska.")
```

\pagebreak


```{r tlike}

m0 = readRDS(here::here(year, 'm22.1', "m22.1.rds")) # 2024 data
m1 = readRDS(here::here(year, 'm22.1a', "m22.1a.rds")) # lognormal srv biomass likelihood
m2 = readRDS(here::here(year, 'm22.1b', "m22.1b.rds")) # iss change
m3 = readRDS(here::here(year, 'm22.1c', "m22.1c.rds")) # maturity change
m4 = readRDS(here::here(year, 'm24', "m24.rds")) # VAST logtnormal


data.frame(Item = c('Catch', 
                    'Survey', 
                    "Fish age", 
                    'Survey age', 
                    'Fish size', 
                    'Recruitment', 
                    'F regularity', 
                    'SPR penalty', 
                    'M prior', 
                    'q prior', 
                    'Objective function'), 
           M22.1 = c(m0$ssqcatch, 
                    m0$like_srv,
                    m0$like_fish_age,
                    m0$like_srv_age, 
                    m0$like_fish_size, 
                    m0$like_rec, 
                    m0$f_regularity, 
                    m0$sprpen, 
                    m0$nll_M, 
                    m0$nll_q, 
                    round(sum(m0$ssqcatch, 
                              m0$like_srv, 
                              m0$like_fish_age, 
                              m0$like_srv_age, 
                              m0$like_fish_size, 
                              m0$like_rec, 
                              m0$f_regularity, 
                              m0$sprpen, 
                              m0$nll_M, 
                              m0$nll_q), 4)),
           
           M22.1a = c(m1$ssqcatch, 
                    m1$like_srv,
                    m1$like_fish_age,
                    m1$like_srv_age, 
                    m1$like_fish_size, 
                    m1$like_rec, 
                    m1$f_regularity, 
                    m1$sprpen, 
                    m1$nll_M, 
                    m1$nll_q, 
                    round(sum(m1$ssqcatch, 
                              m1$like_srv, 
                              m1$like_fish_age, 
                              m1$like_srv_age, 
                              m1$like_fish_size, 
                              m1$like_rec, 
                              m1$f_regularity, 
                              m1$sprpen, 
                              m1$nll_M, 
                              m1$nll_q), 4)),
            M22.1b = c(m2$ssqcatch, 
                    m2$like_srv,
                    m2$like_fish_age,
                    m2$like_srv_age, 
                    m2$like_fish_size, 
                    m2$like_rec, 
                    m2$f_regularity, 
                    m2$sprpen, 
                    m2$nll_M, 
                    m2$nll_q, 
                    round(sum(m2$ssqcatch, 
                              m2$like_srv, 
                              m2$like_fish_age, 
                              m2$like_srv_age, 
                              m2$like_fish_size, 
                              m2$like_rec, 
                              m2$f_regularity, 
                              m2$sprpen, 
                              m2$nll_M, 
                              m2$nll_q), 4)),
            M22.1c = c(m3$ssqcatch, 
                    m3$like_srv,
                    m3$like_fish_age,
                    m3$like_srv_age, 
                    m3$like_fish_size, 
                    m3$like_rec, 
                    m3$f_regularity, 
                    m3$sprpen, 
                    m3$nll_M, 
                    m3$nll_q, 
                    round(sum(m3$ssqcatch, 
                              m3$like_srv, 
                              m3$like_fish_age, 
                              m3$like_srv_age, 
                              m3$like_fish_size, 
                              m3$like_rec, 
                              m3$f_regularity, 
                              m3$sprpen, 
                              m3$nll_M, 
                              m3$nll_q), 4)),
           M24 = c(m4$ssqcatch, 
                    m4$like_srv,
                    m4$like_fish_age,
                    m4$like_srv_age, 
                    m4$like_fish_size, 
                    m4$like_rec, 
                    m4$f_regularity, 
                    m4$sprpen, 
                    m4$nll_M, 
                    m4$nll_q, 
                    round(sum(m4$ssqcatch, 
                              m4$like_srv, 
                              m4$like_fish_age, 
                              m4$like_srv_age, 
                              m4$like_fish_size, 
                              m4$like_rec, 
                              m4$f_regularity, 
                              m4$sprpen, 
                              m4$nll_M, 
                              m4$nll_q), 4))) -> df
df %>% 
   dplyr::mutate(dplyr::across(2:6, round, 3)) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0.5, part = "all")  %>%  
  flextable::set_header_labels(values = 
                                 list(Item = 'Likelihood')) %>% 
  flextable::colformat_num(j=1, big.mark = "") %>% 
  flextable::autofit() %>% 
  flextable::align(j=1, part= "all") %>%  
  flextable::set_caption("Likelihood values for GOA northern rockfish models examined for 2024.")

```

<br>

```{r tparams, eval = T}
source(here::here(year, 'R', 'utils.R'))

pr0 = proj_bio(m0)
pr1 = proj_bio(m1)
pr2 = proj_bio(m2)
pr3 = proj_bio(m3)
pr4 = proj_bio(m4)


data.frame(Item = c('M', 
                    'q', 
                    "Log mean recruitment", 
                    'Log mean F', 
                    'A50 fishery', 
                    'Delta fishery', 
                    'A50 survey', 
                    'Delta survey', 
                    '2023 Total biomass', 
                    '2023 Spawning biomass', 
                    '2023 OFL',
                    '2023 FOFL',
                    '2023 ABC',
                    '2023 FABC'), 
           M22.1 = c(m0$M, 
                    m0$q,
                    m0$log_mean_R,
                    m0$log_mean_F, 
                    m0$a50C, 
                    m0$deltaC, 
                    m0$a50S, 
                    m0$deltaS, 
                    pr0[1,3], 
                    pr0[1,2], 
                    pr0[1,5],
                    pr0[1,7],
                    pr0[1,4],
                    pr0[1,6]),
          M22.1a = c(m1$M, 
                    m1$q,
                    m1$log_mean_R,
                    m1$log_mean_F, 
                    m1$a50C, 
                    m1$deltaC, 
                    m1$a50S, 
                    m1$deltaS, 
                    pr1[1,3], 
                    pr1[1,2], 
                    pr1[1,5],
                    pr1[1,7],
                    pr1[1,4],
                    pr1[1,6]),
          M22.1b = c(m2$M, 
                    m2$q,
                    m2$log_mean_R,
                    m2$log_mean_F, 
                    m2$a50C, 
                    m2$deltaC, 
                    m2$a50S, 
                    m2$deltaS, 
                    pr2[1,3], 
                    pr2[1,2], 
                    pr2[1,5],
                    pr2[1,7],
                    pr2[1,4],
                    pr2[1,6]),
          M22.1c = c(m3$M, 
                    m3$q,
                    m3$log_mean_R,
                    m3$log_mean_F, 
                    m3$a50C, 
                    m3$deltaC, 
                    m3$a50S, 
                    m3$deltaS, 
                    pr3[1,3], 
                    pr3[1,2], 
                    pr3[1,5],
                    pr3[1,7],
                    pr3[1,4],
                    pr3[1,6]),
           M24 = c(m4$M, 
                    m4$q,
                    m4$log_mean_R,
                    m4$log_mean_F, 
                    m4$a50C, 
                    m4$deltaC, 
                    m4$a50S, 
                    m4$deltaS, 
                    pr4[1,3], 
                    pr4[1,2], 
                    pr4[1,5],
                    pr4[1,7],
                    pr4[1,4],
                    pr4[1,6]))%>% 
   dplyr::mutate(across(2:6, round, 3)) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0.5, part = "all")  %>% 
  flextable::colformat_double(i=c(9:11, 13), digit=0) %>% 
  flextable::set_header_labels(values = 
                                 list(Item = 'Parameter/Estimate')) %>% 
  flextable::colformat_num(j=1, big.mark = "") %>% 
  flextable::autofit() %>% 
  flextable::align(j=1, part= "all") %>%  
  flextable::set_caption("Estimates of key parameters for GOA northern rockfish models examined for 2024.")
           
```
\pagebreak


```{r tnumbers, eval = T}
m24 = readRDS(here::here(year, 'm24', 'm24.rds')) 
data.frame(Age = 2:51,
           Abundance = m24$Nat[,64] * 1000,
           Mature = m24$maa * 100,
           Weight = m24$waa,
           Fishery = m24$slx[,1],
           Survey = m24$slx[,2]) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(j=2:3, digit=0) %>% 
  flextable::colformat_double(j=5:6, digit=2) %>% 
  flextable::add_header_row(value = c("", "", "Percent", "", "Selectivity", "Selectivity"), colwidths = rep(1,6)) %>% 
  flextable::merge_at(i=1, j=5:6, part = 'header') %>% 
  flextable::align(i=1, j=5:6, part="header", align = "center") %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::autofit() %>% 
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0, part = "all") %>% 
    flextable::border_remove() %>% 
  flextable::hline_bottom() %>% 
  flextable::hline_top() %>% 
  flextable::hline_top(part="header") %>%  
  flextable::set_caption("Model estimated numbers (thousands), fishery selectivity, and survey selectivity of northern rockfish in the Gulf of Alaska based on the preferred model. Also shown are schedules of age-specific weight and female maturity.")

```

\pagebreak

```{r tcompare, eval = T}
base = readRDS(here::here(year, 'base', 'base.rds')) 
m24 = readRDS(here::here(year, 'm24', 'm24.rds')) 
dat = readRDS(here::here(year, 'm24', "dat.rds")) 

data.frame(year = m24$years,
            cssb = round(m24$spawn_bio)) %>% 
  dplyr::left_join(data.frame(year = base$years,
            pssb = round(base$spawn_bio))) -> ssbs

data.frame(year = m24$years,
            crec = round(m24$recruits, 1)) %>% 
  dplyr::left_join(data.frame(year = base$years,
            prec = round(base$recruits, 1))) -> recs



data.frame(base$Nat * base$waa) %>% 
  dplyr::mutate(age = 2:51) %>% 
  dplyr::filter(age>=6) %>% 
  tidyr::pivot_longer(-age) %>% 
  dplyr::mutate(year = as.numeric(gsub("X", "", name)) + 1960) %>% 
  dplyr::filter(year>=1977) %>% 
  dplyr::group_by(year) %>% 
  dplyr::summarise(psixtot = sum(value)) -> prior_tot

data.frame(m24$Nat * m24$waa) %>% 
  dplyr::mutate(age = 2:51) %>% 
  dplyr::filter(age>=6) %>% 
  tidyr::pivot_longer(-age) %>% 
  dplyr::mutate(year = as.numeric(gsub("X", "", name)) + 1960) %>% 
  dplyr::filter(year>=1977) %>% 
  dplyr::group_by(year) %>% 
  dplyr::summarise(csixtot = sum(value)) -> cur_tot

data.frame(year = dat$years, 
          catch = dat$catch_obs) %>% 
  dplyr::filter(year>=1977) %>% 
  left_join(cur_tot) %>% 
  left_join(prior_tot) %>% 
  mutate(cp = catch / psixtot,
         cc = catch / csixtot) %>% 
  dplyr::select(year, psixtot, csixtot , cp, cc) -> catches
  
ssbs %>% 
  left_join(catches) %>% 
  left_join(recs) %>% 
  dplyr::filter(year>=1977) %>% 
  dplyr::select(Year =year, sPrevious = pssb, sCurrent =cssb, tPrevious=psixtot, tCurrent =csixtot, cPrevious = cp, cCurrent =cc, rPrevious =prec, rCurrent =crec) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(j=4:5, digit=0) %>% 
   flextable::colformat_double(j=6:7, digit=3) %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::autofit() %>% 
  flextable::fontsize(size = 9, part = "all") %>% 
  flextable::padding(padding = 0.8, part = "all") %>% 
  flextable::add_header_row(value = c("", "Spawning biomass", "Spawning biomass", "6+ biomass", "6+ biomass", "Catch/6+ biomass", "Catch/6+ biomass", "Age-2+ recruits", "Age-2+ recruits"), colwidths = rep(1,9)) %>% 
  flextable::border_remove() %>% 
  flextable::merge_at(i=1, j=c(2:3), part = 'header') %>% 
  flextable::merge_at(i=1, j=c(4:5), part = 'header') %>% 
  flextable::merge_at(i=1, j=c(6:7), part = 'header') %>% 
  flextable::merge_at(i=1, j=c(8:9), part = 'header') %>% 
  flextable::align(i=1, part="header", align = "center") %>% 
  flextable::align(j=1, part="all") %>% 
  flextable::hline_bottom() %>% 
  flextable::hline_top() %>% 
  flextable::hline_top(part="header") %>% 
  flextable::colformat_num(j=1, big.mark="") %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::set_header_labels(values = list(sPrevious = "Previous",
                                             tPrevious = "Previous",
                                             cPrevious = "Previous",
                                             rPrevious = "Previous",
                                             sCurrent = "Current",
                                             tCurrent ="Current",
                                             cCurrent = "Current",
                                             rCurrent = "Current")) %>%  
  flextable::set_caption("Comparison of 2022 estimated time series of female spawning biomass, 6+ biomass (age 6 and greater), catch/(6+ biomass), and the number of age-2+ recruits for northern rockfish in the Gulf of Alaska compared with 2020 estimates.")

```
\pagebreak
```{r tmcmcpar}

readRDS(here::here(year, 'm24', 'mcmcpars.rds')) %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::autofit() %>% 
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 1, part = "all") %>% 
  flextable::colformat_double(i=c(1, 4:5), digits=3) %>% 
  flextable::colformat_double(i=2:3, digits=0) %>% 
  flextable::add_header_row(
    value = c("",  "", "mu", "Median", "σ", "BCI", "BCI"), colwidths = rep(1,7)) %>% 
  flextable::border_remove() %>% 
  flextable::hline_bottom() %>% 
  flextable::hline_top() %>% 
  flextable::align(part="all", j=1, align="left") %>% 
  flextable::hline_top(part="header") %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::set_header_labels(values = list(name = "Parameter",
                                             value = "mu",
                                             mean = "MCMC",
                                             median = "MCMC",
                                             sd = "MCMC",
                                             lci = "Lower",
                                             uci = "Upper")) %>%
  flextable::set_caption("Estimates of key parameters andoutputs with MCMC estimates of mean, median, standard deviations σ_MCMC, and 95% Bayesian credible intervals (BCI) derived from MCMC.")
```
\pagebreak

```{r ttimseries, eval = T}

tbl = readRDS(here::here(year, 'data', 'output', 'mcmc_tbl.rds'))


tbl %>% 
  flextable::flextable() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::autofit() %>% 
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::padding(padding = 0.8, part = "all") %>% 
  flextable::colformat_int(j=1, big.mark="") %>% 
  flextable::colformat_double(j=2:10, digits = 0) %>% 
  flextable::add_header_row(value = c("", "Age 2+ recruits", "Age 2+ recruits", "Age 2+ recruits", "Total biomass", "Total biomass", "Total biomass", "Spawning biomass", "Spawning biomass", "Spawning biomass"), colwidths = rep(1,10)) %>% 
  flextable::border_remove() %>% 
  flextable::merge_at(i=1, j=c(2:4), part = 'header') %>% 
  flextable::merge_at(i=1, j=c(5:7), part = 'header') %>% 
  flextable::merge_at(i=1, j=c(8:10), part = 'header') %>% 
  flextable::align(i=1, part="header", align = "center") %>% 
  flextable::hline_bottom() %>% 
  flextable::hline_top() %>% 
  flextable::align(part="all", j=1, align="left") %>% 
  flextable::hline_top(part="header") %>% 
  flextable::set_header_labels(values = list(year = "Year",
                                             mean = "Mean",
                                             q1 = "2.5%",
                                             q2 = "97.5%",
                                             mean_tp = "Mean",
                                             q1_tp = "2.5%",
                                             q2_tp = "97.5%",
                                             mean_sp = "Mean",
                                             q1_sp = "2.5%",
                                             q2_sp = "97.5%")) %>%  
  flextable::autofit() %>% 
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Estimated time series of number at age-2 recruits (thousands), total biomass, and female spawning biomass with 95% confidence bounds for northern rockfish in the Gulf of Alaska, from this year’s model MCMC results.")

```
\pagebreak 

```{r tsb}
read.csv(here::here(year, 'm24', 'processed', 'mscen_ssb.csv')) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(j=2:8, digits = 0) %>% 
  flextable::border_remove() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::add_header_row(value = c("", "Maximum", "Author's F", "Half", "5-year", "No", "", "Approaching"), colwidths = rep(1, 8))  %>% 
  flextable::set_header_labels(values = list(
    maxf = "permissible F",
    authf = "(Estimated catches)",
    half_maxf = "maximum F",
    avg5f = "average F",
    nof = "Fishing",
    overf = "Overfishing",
    appoverf = "overfished")) %>% 
  # flextable::colformat_double( digits = 0) %>% 
  flextable::hline_bottom() %>% 
  flextable::hline_top() %>% 
  flextable::align(part="all", j=1, align="left") %>% 
  flextable::hline_top(part="header") %>% 
  # flextable::merge_at(i=1, j=1:8) %>% 
  # flextable::align(part="body", i=1, align="center") %>% 
  # flextable::merge_at(i=16, j=1:8) %>% 
  # flextable::align(part="body", i=16, align="center") %>% 
  # flextable::merge_at(i=31, j=1:8) %>% 
  # flextable::align(part="body", i=31, align="center") %>% 
  flextable::width(j=1, width=0.5) %>% 
  flextable::padding(padding = 0, part = "all") %>% 
  flextable::colformat_int(j=1, big.mark="") %>% 
  flextable::align(j=2:8, align="center", part = 'all') %>% 
  flextable::autofit()  %>%  
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Set of projections of female spawning biomass for northern rockfish in the Gulf of Alaska. Six harvest scenarios designed to satisfy the requirements of Amendment 56, NEPA, and MSFCMA. For a description of scenarios see section *Harvest Recommendations*.")
  

```
\pagebreak 

```{r tf, eval = T}
read.csv(here::here(year, 'm24', 'processed', 'mscen_f.csv')) %>% 
  flextable::flextable() %>% 
  # flextable::colformat_double(j=2:8, digits = 0) %>% 
  flextable::border_remove() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::add_header_row(value = c("", "Maximum", "Author's F", "Half", "5-year", "No", "", "Approaching"), colwidths = rep(1, 8))  %>% 
  flextable::set_header_labels(values = list(
    maxf = "permissible F",
    authf = "(Estimated catches)",
    half_maxf = "maximum F",
    avg5f = "average F",
    nof = "Fishing",
    overf = "Overfishing",
    appoverf = "overfished")) %>% 
  # flextable::colformat_double( digits = 0) %>% 
  flextable::hline_bottom() %>% 
  flextable::hline_top() %>% 
  flextable::align(part="all", j=1, align="left") %>% 
  flextable::hline_top(part="header") %>% 
  # flextable::merge_at(i=1, j=1:8) %>% 
  # flextable::align(part="body", i=1, align="center") %>% 
  # flextable::merge_at(i=16, j=1:8) %>% 
  # flextable::align(part="body", i=16, align="center") %>% 
  # flextable::merge_at(i=31, j=1:8) %>% 
  # flextable::align(part="body", i=31, align="center") %>% 
  flextable::width(j=1, width=0.5) %>% 
  flextable::padding(padding = 0, part = "all") %>% 
  flextable::colformat_int(j=1, big.mark="") %>% 
  flextable::align(j=2:8, align="center", part = 'all') %>% 
  flextable::autofit()  %>%  
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Set of projections of Fishing mortality for northern rockfish in the Gulf of Alaska. Six harvest scenarios designed to satisfy the requirements of Amendment 56, NEPA, and MSFCMA. For a description of scenarios see section *Harvest Recommendations*.")
  
```

\pagebreak 

```{r tyld, eval = T}
read.csv(here::here(year, 'm24', 'processed', 'mscen_yld.csv')) %>% 
  flextable::flextable() %>% 
  flextable::colformat_double(j=2:8, digits = 0) %>%
  flextable::border_remove() %>% 
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 10, part = "all") %>% 
  flextable::add_header_row(value = c("", "Maximum", "Author's F", "Half", "5-year", "No", "", "Approaching"), colwidths = rep(1, 8))  %>% 
  flextable::set_header_labels(values = list(
    maxf = "permissible F",
    authf = "(Estimated catches)",
    half_maxf = "maximum F",
    avg5f = "average F",
    nof = "Fishing",
    overf = "Overfishing",
    appoverf = "overfished")) %>% 
  # flextable::colformat_double( digits = 0) %>% 
  flextable::hline_bottom() %>% 
  flextable::hline_top() %>% 
  flextable::align(part="all", j=1, align="left") %>% 
  flextable::hline_top(part="header") %>% 
  # flextable::merge_at(i=1, j=1:8) %>% 
  # flextable::align(part="body", i=1, align="center") %>% 
  # flextable::merge_at(i=16, j=1:8) %>% 
  # flextable::align(part="body", i=16, align="center") %>% 
  # flextable::merge_at(i=31, j=1:8) %>% 
  # flextable::align(part="body", i=31, align="center") %>% 
  flextable::width(j=1, width=0.5) %>% 
  flextable::padding(padding = 0, part = "all") %>% 
  flextable::colformat_int(j=1, big.mark="") %>% 
  flextable::align(j=2:8, align="center", part = 'all') %>% 
  flextable::autofit()  %>%  
  flextable::fit_to_width(6.5) %>% 
  flextable::set_caption("Set of projections of Fishing yield for northern rockfish in the Gulf of Alaska. Six harvest scenarios designed to satisfy the requirements of Amendment 56, NEPA, and MSFCMA. For a description of scenarios see section *Harvest Recommendations*.")
  
```

