# Data Gaps and Research Priorities

## Life history and habitat utilization

There is little information on larval, post-larval, or early life history stages of northern rockfish. 
Habitat requirements for larval, post-larval, and early stages are mostly unknown. 
Habitat requirements for later stage juvenile and adult fish are anecdotal or conjectural. 
Research needs to be done on the bottom habitat of the major fishing grounds, on what HAPC biota are found on these grounds, and on what impact bottom trawling may have on these biota.
Given the substantial influence of maturity-at-age on management quantities (i.e., ABC) and observations of skip spawning [@Conrath2019] we strongly suggest that continued research be devoted to collecting maturity-at-age data for northern and other Gulf of Alaska rockfish. 
A first pass at examining the effect of the skip spawning levels reported in [@Conrath2019] shows a decrease in estimated spawning biomass (Figure 10-\@ref(fig:fskip)).
A proposal is currently in the process of being developed that would collect a larger sample size for northern rockfish and compare maturity at age estimates to previous studies. 
If funded, additional data collected as part of this study would be used to investigate possible time-dependent maturity.

## Assessment Data

The highly variable design-based biomass estimates for northern rockfish from bottom trawl survey suggest that the stratified random design of the surveys does a relatively poor job of assessing stock condition of northern rockfish and that a different survey approach may be needed to reduce the variability in biomass estimates. 
In particular, the last CIE review report recommended that assumptions about extending area-swept estimates of biomass in trawlable versus untrawlable grounds may impact catchability assumptions. 
The AFSC is currently undertaking a study on habitat classifications so that assumptions about catchability, in particular, time-dependent changes in catchability, can be more rigorously established.
To address some of these issues the design-based index has been replaced with a model-based survey biomass index generated by a Vector Autoregressive Spatio-Temporal (VAST) model. 
The benefits of the VAST model-based approach to survey index standardization are that as a delta-model it partitions the likelihood of trawl survey observations between encounter probability and positive catch rate components, and accounts for spatial and spatio-temporal correlations in survey catch rates.
However, this model could benefit from continued examination of appropriate parameterization for northern rockfish which are found in highly "patchy" distributions.
Given the high precision of VAST outputs it may prove valuable to the incorporating  of an error inflation parameter to increase the variance in VAST models and explore the effect low survey model variance has on resulting assessment outputs.

