---
bibliography: ["VAST_safe.bib"]   
csl: "fishfish.csl"
---
\newpage
# Appendix 10b: VAST model-based abundance 

## Background

Model-based abundance indices have a long history of development in fisheries (Maunder and Punt 2004). 
We here use a delta-model that uses two linear predictors (and associated link functions) to model the probability of encounter and the expected distribution of catches (in biomass or numbers, depending upon the specific stock) given an encounter (Lo *et al*. 1992; Stefánsson 1996).  
Previous research has used spatial strata (either based on strata used in spatially stratified design, or post-stratification) to approximate spatial variation (Helser *et al*. 2004), although recent research suggests that accounting for spatial heterogeneity within a single stratum using spatially correlated residuals and habitat covariates can improve precision for the wrestling index (Shelton *et al*. 2014).  
Model-based indices have been used by the Pacific Fisheries Management Council to account for intra-class correlations among hauls from a single contract vessel since approximately 2004 (Helser *et al*. 2004).  
Specific methods evolved over time to account for strata with few samples (Thorson and Ward 2013), and eventually to improve precision based on spatial correlations (Thorson *et al*. 2015) using what became the Vector Autoregressive Spatio-temporal (VAST) model (Thorson and Barnett 2017).

The performance of VAST has been evaluated previously using a variety of designs.  
Research has showed improved performance estimating relative abundance compared with spatially-stratified index standardization models (Grüss and Thorson 2019; Thorson *et al*. 2015), while other simulation studies have shown unbiased estimates of abundance trends (Johnson *et al*. 2019).  
Brodie *et al*. (2020) showed improved performance in estimating index scale given simulated data relative to generalized additive and machine learning models.  
Using real-world case studies, Cao *et al*. (2017) showed how random variation in the placement of tows relative to high-quality habitat could be “controlled for” using a spatio-temporal framework, and OLeary *et al*. (2020) showed how combining surveys from the eastern and northern Bering Sea within a spatio-temporal framework could assimilate spatially unbalanced sampling in those regions. Other characteristics of model performance have also been simulation-tested although these results are not discussed further here.  

## Settings used in 2021
The software versions of dependent programs used to generate VAST estimates were:  

`R (>=4.1.0), INLA (21.02.23), TMB (1.7.18), TMBhelper (1.3.0), VAST (3.6.1),  FishStatsUtils (2.8.0)`

We used a Poisson-link delta-model (Thorson 2018) involving two linear predictors, and a gamma or lognormal distribution to model positive catch rates. 
We extrapolated catch density using 3705 m (2 nmi) X 3705 m (2 nmi) extrapolation-grid cells; this results in 36,690 extrapolation-grid cells for the eastern Bering Sea, 15,079 in the northern Bering Sea  and 26,510 for the Gulf of Alaska (some Gulf of Alaska analyses eliminated the deepest stratum with depths >700 m because of sparse observations, resulting in a 22,604-cell extrapolation grid). 
We used bilinear interpolation to interpolate densities from 750 “knots” to these extrapolation-grid cells (i.e, using `fine_scale=TRUE` feature); knots were approximately evenly distributed over space, in proportion to the dimensions of the extrapolation grid. 
We estimated geometric anisotropy (how spatial autocorrelation declines with differing rates over distance in some cardinal directions than others), and included a spatial and spatio-temporal term for both linear predictors. 
To facilitate interpolation of density between unsampled years, we specified that the spatio-temporal fields were structured over time as an AR(1) process (where the magnitude of autocorrelation was estimated as a fixed effect for each linear predictor). 
However, we did not include any temporal correlation for intercepts, which we treated as fixed effects for each linear predictor and year. 
Finally, we used epsilon bias-correction to correct for retransformation bias (Thorson and Kristensen 2016). 

### Diagnostics

We checked model fits for evidence of non-convergence by confirming that (1) the derivative of the marginal likelihood with respect to each fixed effect was sufficiently small and (2) that the Hessian matrix was positive definite.  
We then checked for evidence of model fit by computing Dunn-Smyth randomized quantile residuals (Dunn and Smyth 1996) and visualizing these using a quantile-quantile plot within the DHARMa R package.  
We also evaluated the distribution of these residuals over space in each year, and inspected them for evidence of residual spatio-temporal patterns. 


## References {-}
Brodie, S.J., Thorson, J.T., Carroll, G., et al. (2020) Trade-offs in covariate selection for species distribution models: A methodological comparison. Ecography 43, 11–24.

Cao, J., Thorson, J., Richards, A. and Chen, Y. (2017) Geostatistical index standardization improves the performance of stock assessment model: An application to northern shrimp in the Gulf of Maine. Canadian Journal of Fisheries and Aquatic Sciences.

Dunn, K.P., and Smyth, G.K. 1996. Randomized quantile residuals. Journal of Computational and Graphical Statistics 5, 1-10.

Grüss, A. and Thorson, J.T. (2019) Developing spatio-temporal models using multiple data types for evaluating population trends and habitat usage. ICES Journal of Marine Science 76, 1748–1761.

Helser, T.E., Punt, A.E. and Methot, R.D. (2004) A generalized linear mixed model analysis of a multi-vessel fishery resource survey. Fisheries Research 70, 251–264.

Johnson, K.F., Thorson, J.T. and Punt, A.E. (2019) Investigating the value of including depth during spatiotemporal index standardization. Fisheries Research 216, 126–137.

Lo, N.C.-h., Jacobson, L.D. and Squire, J.L. (1992) Indices of relative abundance from fish spotter data based on delta-lognornial models. Canadian Journal of Fisheries and Aquatic Sciences 49, 2515–2526.

Maunder, M.N. and Punt, A.E. (2004) Standardizing catch and effort data: A review of recent approaches. Fisheries research 70, 141–159.

O’Leary, C.A., Thorson, J.T., Ianelli, J.N. and Kotwicki, S. Adapting to climate-driven distribution shifts using model-based indices and age composition from multiple surveys in the walleye pollock (gadus chalcogrammus) stock assessment. Fisheries Oceanography.

Shelton, A.O., Thorson, J.T., Ward, E.J. and Feist, B.E. (2014) Spatial semiparametric models improve estimates of species abundance and distribution. Canadian Journal of Fisheries and Aquatic Sciences 71, 1655–1666.

Stefánsson, G. (1996) Analysis of groundfish survey abundance data: Combining the GLM and delta approaches. ICES journal of Marine Science 53, 577–588.

Thorson, J.T. (2018) Three problems with the conventional delta-model for biomass sampling data, and a computationally efficient alternative. Canadian Journal of Fisheries and Aquatic Sciences 75, 1369–1382.

Thorson, J.T. and Barnett, L.A. (2017) Comparing estimates of abundance trends and distribution shifts using single-and multispecies models of fishes and biogenic habitat. ICES Journal of Marine Science 74, 1311–1321.

Thorson, J.T. and Kristensen, K. (2016) Implementing a generic method for bias correction in statistical models using random effects, with spatial and population dynamics examples. Fisheries Research 175, 66–74.

Thorson, J.T., Shelton, A.O., Ward, E.J. and Skaug, H.J. (2015) Geostatistical delta-generalized linear mixed models improve precision for estimated abundance indices for West Coast groundfishes. ICES Journal of Marine Science 72, 1297–1310.

Thorson, J.T. and Ward, E.J. (2013) Accounting for space–time interactions in index standardization models. Fisheries Research 147, 426–433.