\allsectionsfont{\raggedright}
# Projections and Status Determination

A standard set of projections is required for each stock managed under Tiers 1, 2, or 3 of Amendment 56. 
This set of projections encompasses seven harvest scenarios designed to satisfy the requirements of Amendment 56, the National Environmental Policy Act, and the Magnuson-Stevens Fishery Conservation and Management Act (MSFCMA).
For each scenario, the projections begin with the vector of `r year-1` numbers at age as estimated in the previous full assessment. 
This vector is then projected forward to the beginning of `r year+1` using the schedules of natural mortality and selectivity described in the previous full assessment and the best available estimate of total (year-end) catch for `r year` 
In each subsequent year, the fishing mortality rate is prescribed on the basis of the spawning biomass in that year and the respective harvest scenario. 
In each year, recruitment is drawn from an inverse Gaussian distribution whose parameters consist of maximum likelihood estimates determined from recruitments estimated in the previous full assessment. 
Spawning biomass is computed in each year based on the time of peak spawning and the maturity and weight schedules described in the assessment. 
Total catch after `r year` is assumed to equal the catch associated with the respective harvest scenario in all years. 
This projection scheme is run 1,000 times to obtain distributions of possible future stock sizes, fishing mortality rates, and catches.

Five of the seven standard scenarios will be used in an Environmental Assessment prepared in conjunction with the final SAFE. 
These five scenarios, which are designed to provide a range of harvest alternatives that are likely to bracket the final TAC for `r year+1`, are as follow ($max F_{ABC}$ refers to the maximum permissible value of $F_{ABC}$ under Amendment 56):

Scenario 1:  In all future years, *F* is set equal to max $F_{ABC}$. (Rationale: Historically, TAC has been constrained by ABC, so this scenario provides a likely upper limit on future TACs.)

Scenario 2:  In `r year+1` and `r year+2` *F* is set equal to a constant fraction of $max F_{ABC}$, where this fraction is equal to the ratio of the realized catches in 2015-2017 to the ABC recommended in  the assessment for each of those years. 
For the remainder of the future years, maximum  permissible ABC is used. 
(Rationale: In many fisheries the ABC is routinely not fully  utilized, so assuming an average ratio catch to ABC will yield more realistic projections.)

Scenario 3:  In all future years, *F* is set equal to 50\% of $max F_{ABC}$. (Rationale: This scenario provides a likely lower bound on $F_{ABC}$ that still allows future harvest rates to be adjusted downward when stocks fall below reference levels.)

Scenario 4:  In all future years, *F* is set equal to the 2013-2017 average *F*. (Rationale: For some stocks, TAC can be well below ABC, and recent average *F* may provide a better indicator of FTAC than $F_{ABC}$)

Scenario 5:  In all future years, *F* is set equal to zero. (Rationale: In extreme cases, TAC may be set at a level close to zero.)

Two other scenarios are needed to satisfy the MSFCMA’s requirement to determine whether a stock is currently in an overfished condition or is approaching an overfished condition. These two scenarios are as follows (for Tier 3 stocks, the MSY level is defined as B35%):

Scenario 6:  In all future years, F is set equal to $F_{OFL}$. 
(Rationale: This scenario determines whether a stock is overfished. 
If the stock is expected to be 1) above its MSY level in 2018 or 2) above ½ of its MSY level in 2018 and above its MSY level in 2028 under this scenario, then the stock is not overfished.)

Scenario 7:  In `r year+1` and `r year+2`, *F* is set equal to max $F_{ABC}$, and in all subsequent years *F* is set equal to $F_{OFL}$. (Rationale: This scenario determines whether a stock is approaching an overfished condition. 
If the stock is 1) above its MSY level in `r year+2` or 2) above 1/2 of its MSY level in `r year+2` and expected to be above its MSY level in `r year+14` under this scenario, then the stock is not approaching an overfished condition.)

Spawning biomass, fishing mortality, and yield are tabulated for the seven standard projection scenarios (Table 12-1). 
The difference for this assessment for projections is in Scenario 2 (Author’s *F*); we use pre-specified catches to increase accuracy of short-term projections in fisheries where the catch is usually less than the ABC. This was suggested to help management with setting preliminary ABCs and OFLs for two-year ahead specifications.

