---
title: "10. Assessment of the Northern Rockfish stock in the Gulf of Alaska"
output: 
   bookdown::pdf_document2:
     reference_docx: "template.docx"
     toc: false
     number_sections: false
     css: "styles.css"

always_allow_html: true        
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in
      
fig_caption: true
bibliography: "safe_bibby.bib"
csl: "fishfish.csl"

author: "Benjamin C. Williams, Peter-John F. Hulson, Chris R. Lunsford"
date: "November 2021"

header-includes:
   \usepackage[labelsep=period]{caption}
   \usepackage{multirow}
   \usepackage{float}
   \usepackage{booktabs}
   \usepackage{colortbl}
   \usepackage{graphicx}
   \usepackage{sectsty}
   \usepackage{babel}
   \allsectionsfont{\centering}
   \usepackage{array}
   \newcolumntype{R}{>{\centering\arraybackslash}m{1.9cm}}
   \newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
   \usepackage{titlesec}
   \titlespacing\section{-5pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
   \renewcommand{\thefigure}{10-\arabic{figure}}
   \renewcommand{\thetable}{10-\arabic{table}}
---
\pagenumbering{gobble}

```{r setup, include=FALSE, echo = FALSE}
# remotes::install_github("crsh/rmdfiltr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "!h", out.extra = "")
knitr::opts_knit$set(eval.after = "fig.cap")
```

```{r load, warning=F, message=F}
library(dplyr)
year = 2021
model = "base"
end_proj = year + 15
```
```{r load2, eval = T}
vroom::vroom(here::here(year, "data", "raw", "fsh_catch_data.csv")) %>% 
   summarise(date = max(WEEK_END_DATE)) %>% 
   pull(date) -> catch_date
catch = read.csv(here::here(year, "data/output/fsh_catch.csv"))
yld = read.csv(here::here(year, "data/output/yld_rat.csv"))
data_pull = read.table(here::here(year, "data/raw/data_called.txt"))[2,1]
data_pull2 <- paste(lubridate::month(data_pull, label = TRUE, abbr = FALSE), lubridate::day(data_pull))
```


```{r, child="01-summary.Rmd", eval = T}

```


```{r, child="02-status.Rmd", eval = F}

```

```{r, child="03-responses.Rmd", eval = T}

```


```{r, child = c("04-intro.Rmd", "05-fishery.Rmd", "06-data.Rmd", "07-model.Rmd"), eval = F}

```

```{r, child = c("08-results.Rmd", "09-abc.Rmd", "10-ecosystem.Rmd", "11-gaps.Rmd"), eval = F}

```

\pagebreak
\allsectionsfont{\centering}
# References
<div id="refs"></div>

```{r, child = c("12-tables.Rmd"), eval = F}

```


```{r, child = c("13-figures.Rmd"), eval = T}

```

\pagebreak

```{r, child = c("14-append_a.Rmd"), eval = F}

```

```{r, child = c("14-append_a.Rmd", "15-append_vast.Rmd"), eval = F}

```
