## Responses to SSC and Plan Team Comments on Assessments in General
> “The SSC supports the JGPT’s recommendation that stock assessment authors transition from the ADMB RE variants to the rema framework, which implements the same model variants in a single framework with several improvements.”(SSC, Oct 2022)  

This model current implements the rema framework for apportionment. 
However, the current rema model uses the design-based survey biomass estimates as inputs. 
As this model uses VAST instead of design-based survey biomass examinations of changing to regional VAST data estimates will be explored in the next full assessment.

## Responses to SSC and Plan Team Comments Specific to this Assessment

> "The SSC supports the GOA GPT recommendations to investigate potential mechanisms for the
underlying pattern [to the fishery length composition] and recommends the authors consider whether a selectivity time block, to account for changes in the fishery (i.e., POP rebuilding), is appropriate and improves fit to the compositional information." (SSC December 2022)  

> "The SSC notes the MCMC on the estimates of q include a long right tail with unrealistic values of q. The
SSC requests the authors investigate a model run with a fixed M." (SSC December 2022) 


> "The SSC also requests the following for future assessments: bubble plots of Pearson residuals for all age
and length data, including the sign and scale of residuals; and inclusion of a figure showing changes in
previous VAST estimates due to updating with new survey information." (SSC December 2022)

Model runs addressing the above requests will be examined in the next full assessment.

> "The SSC reiterates its past support of empirical
research projects on maturity and skip spawning, perhaps with industry partnership."(SSC December 2022)  

Examinations of maturity and skip spawning are ongoing.

